# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='summit',
    version='0.5.0',
    description='Tools for optimizing chemical processes',
    python_requires='==3.*,>=3.6.1',
    project_urls={
        'homepage': 'https://github.com/sustainable-processes/summit',
        'repository': 'https://github.com/sustainable-processes/summit'
    },
    author='Kobi Felton',
    author_email='kobi.c.f@gmail.com',
    maintainer='Jan Rittig',
    license='MIT',
    keywords='machine-learning chemistry reactions optimization neural-networks drug-discovery bayesian-optimization nelder-mead snobfit gryffin TSEMO',
    packages=[
        'summit', 'summit.benchmarks', 'summit.benchmarks.experiment_emulator',
        'summit.strategies', 'summit.utils'
    ],
    package_data={
        'summit.benchmarks.experiment_emulator': [
            'data/*.csv', 'data/*.md', 'data/*.xlsx',
            'trained_models/BNN/*.json', 'trained_models/BNN/*.png',
            'trained_models/BNN/*.pt'
        ]
    },
    install_requires=[
        'blitz-bayesian-pytorch==0.2.3', 'fastprogress==0.*,>=0.2.3',
        'gpy==1.*,>=1.9.0', 'gpyopt==1.*,>=1.2.6', 'gryffin',
        'ipywidgets==7.*,>=7.5.1', 'matplotlib==3.*,>=3.2.2', 'numpy==1.18.0',
        'pandas==1.*,>=1.1.0', 'pymoo==0.*,>=0.4.1', 'pyrff==1.*,>=1.0.1',
        'sqsnobfit==0.*,>=0.4.3', 'tensorflow==2.*,>=2.2.0',
        'tensorflow-estimator<2.3.0,>=2.2.0',
        'tensorflow-probability==0.*,>=0.10.1', 'torch==1.*,>=1.4.0'
    ],
    dependency_links=[
        'git+https://github.com/sustainable-processes/gryffin@0.1.1#egg=gryffin',
        'git+https://github.com/jbardin/scp.py@v0.13.2#egg=scp'
    ],
    extras_require={
        'dev': [
            'black==20.*,>=20.8.0', 'ipdb==0.*,>=0.13.2',
            'nbsphinx==0.*,>=0.7.1', 'pytest==3.*,>=3.0.0',
            'rope==0.*,>=0.17.0', 'sphinx==3.*,>=3.2.1',
            'sphinx-rtd-theme==0.*,>=0.5.0'
        ],
        'experiments': [
            'hiplot==0.*,>=0.1.12', 'neptune-client==0.*,>=0.4.115',
            'neptune-contrib[viz]==0.*,>=0.22.0', 'paramiko==2.*,>=2.7.1', 'scp'
        ]
    },
)
